name: ${COMPOSE_PROJECT_NAME:?COMPOSE_PROJECT_NAME is required}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../:/workspace:cached
      - node_modules:/workspace/node_modules
    command: sleep infinity
    tty: true

volumes:
  node_modules:
